[project]
name = "aimath-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.49.1",
    "jinja2>=3.1.6",
    "openai>=2.5.0",
    "opencv-python>=4.12.0.88",
    "python-dotenv>=1.1.1",
]
